package markdown

import (
	"bytes"
	"fmt"
	"regexp"
	"strings"

	"github.com/ihaaae/yanki/internal/note"
	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/ast"
)

const boilerplateComment = "<!-- This HTML was generated by Yanki, a Markdown to Anki converter. Do not edit directly. -->"

var (
	tagRegex        = regexp.MustCompile(`(?s)<[^>]*>`)
	mediaTagRegex   = regexp.MustCompile(`(?i)<(img|video|audio|iframe|object|embed|canvas|svg|picture)\b`)
	firstDivEndTag  = regexp.MustCompile(`(?s)^(<div[^>]*>)`)
	nonAlphanumeric = regexp.MustCompile(`[^\dA-Za-z]+`)
	collapseSpaces  = regexp.MustCompile(` +`)
)

// buildDocument reparents nodes into a fresh document so a subset of a parsed
// tree can be rendered on its own.
func buildDocument(nodes []ast.Node) *ast.Document {
	document := ast.NewDocument()

	for _, node := range nodes {
		node.SetParent(nil)
		node.SetPreviousSibling(nil)
		node.SetNextSibling(nil)
		document.AppendChild(document, node)
	}

	return document
}

// renderBlocks renders a slice of block nodes to HTML.
func renderBlocks(md goldmark.Markdown, nodes []ast.Node, source []byte) (string, error) {
	document := buildDocument(nodes)

	var buffer bytes.Buffer
	if err := md.Renderer().Render(&buffer, source, document); err != nil {
		return "", fmt.Errorf("render markdown: %w", err)
	}

	return buffer.String(), nil
}

// renderField renders one card field: the block HTML wrapped in a classed div,
// with a generated-content comment and an optional empty placeholder.
func renderField(md goldmark.Markdown, nodes []ast.Node, source []byte, opts Options, model note.ModelName, position string, useEmptyPlaceholder bool) (string, error) {
	rendered, err := renderBlocks(md, nodes, source)
	if err != nil {
		return "", err
	}

	empty := isVisuallyEmpty(rendered)
	if empty && !useEmptyPlaceholder {
		return "", nil
	}

	wrapped := wrapHTML(rendered, opts.Namespace, model, position)

	if empty {
		wrapped = insertPlaceholder(wrapped)
	}

	return boilerplateComment + "\n" + strings.TrimSpace(wrapped), nil
}

// wrapHTML wraps rendered field HTML in the div that carries Yanki's styling
// classes.
func wrapHTML(rendered, namespace string, model note.ModelName, position string) string {
	classes := []string{
		note.CSSDefaultClassName,
		"namespace-" + namespace,
		position,
		"model-" + string(model),
	}

	cleaned := make([]string, 0, len(classes))
	for _, class := range classes {
		cleaned = append(cleaned, cleanClassName(class))
	}

	return fmt.Sprintf(`<div class="%s">%s</div>`, strings.Join(cleaned, " "), rendered)
}

// cleanClassName mirrors the class-name normalization the original
// implementation used, so custom CSS keeps matching.
func cleanClassName(className string) string {
	cleaned := strings.ToLower(className)
	cleaned = nonAlphanumeric.ReplaceAllString(cleaned, " ")
	cleaned = strings.TrimSpace(cleaned)
	cleaned = collapseSpaces.ReplaceAllString(cleaned, "-")

	return cleaned
}

// insertPlaceholder puts the empty placeholder inside the first div, matching
// where real content would go.
func insertPlaceholder(wrapped string) string {
	placeholder := "<p><em>" + note.DefaultEmptyText + "</em></p>"

	return firstDivEndTag.ReplaceAllString(wrapped, "${1}"+placeholder)
}

// isVisuallyEmpty reports whether rendered HTML has no content a learner would
// see.
func isVisuallyEmpty(rendered string) bool {
	if mediaTagRegex.MatchString(rendered) {
		return false
	}

	return strings.TrimSpace(tagRegex.ReplaceAllString(rendered, "")) == ""
}
